name: Run main.py

on:
  workflow_dispatch:

env:
  GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
  LLM_MODEL: ${{ secrets.LLM_MODEL }}
  EMBEDDING_MODEL: ${{ secrets.EMBEDDING_MODEL }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4  # Updated to v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.0'  # Install the required Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv sync || pip install -r requirements.txt  # Fallback if uv sync fails

      - name: Run main.py
        run: python main.py
